project_path: /Users/tony/reps/github/anton-pershin/llm-assistant
result_dir: ${user_settings.project_path}
hydra_root: ${user_settings.result_dir}/hydra
hydra_dir: ${user_settings.hydra_root}/${now:%Y-%m-%d}/${now:%H-%M-%S}

markdown_collections:
  management:
    path: /Users/tony/reps/github/anton-pershin/management-notes
    description: "Management notes and documentation"
  general:
    path: /Users/tony/reps/github/anton-pershin/general-notes
    description: "General notes (books, articles etc.)"
  it:
    path: /Users/tony/reps/github/anton-pershin/it-notes
    description: "IT notes"

llm_server_url: http://localhost:9191/v1/chat/completions

