_target_: llmass.modes.recent_papers
_partial_: true
_args_:
  - - 
      url: "https://rss.arxiv.org/rss/cs.LG"
      name: "cs.LG"
    - 
      url: "https://rss.arxiv.org/rss/cs.CL"
      name: "cs.CL"
    - 
      url: "https://rss.arxiv.org/rss/cs.AI"
      name: "cs.AI"
  - ${now:%Y_%m_%d}_relevant_arxiv_papers.md  # output filename
